bornieproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.template import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^logout/$', auth_views.logout, name='logout_next'),
    url(r'^', include('mainApp.urls')),
]

mainApp/urls.py
from django.conf.urls import url

app_name='mainapp'
from . import views, data_views


urlpatterns = [
    url(r'^$', data_views.HomeView.as_view(), name="home"),
    url(r'^labs/$', views.LabsView.as_view(), name="labs"),
    url(r'^labs/add/$', views.LabAddView.as_view(), name="lab-add"),
    url(r'^labs/(?P<pk>[0-9]+)/$',views.LabsDetail.as_view(), name="lab-detail"),
    url(r'^labs/(?P<pk>[0-9]+)/update/$',views.LabUpdate.as_view(), name="lab-update"),

    url(r'^users/$', views.UsersView.as_view(), name="users"),
    url(r'^users/(?P<pk>[0-9]+)/$',views.UsersDetail.as_view(), name="user-detail"),
    url(r'^users/add/$',views.UserAddView.as_view(),name="user-add"),
    url(r'^users/(?P<pk>[0-9]+)/update/$',views.UserUpdateView.as_view(),name="user-update"),

    url(r'^parameters/$', data_views.TestParameterList.as_view(), name="parameters"),
    url(r'^parameters/add/$', data_views.TestParameterAdd.as_view(), name="parameter-add"),
    url(r'^parameters/(?P<pk>[0-9]+)/$', data_views.TestParameterDetail.as_view(), name="parameter-detail"),
    url(r'^parameters/(?P<pk>[0-9]+)/update$', data_views.TestParameterUpdate.as_view(), name="parameter-update"),

    #url(r'^testdata/$', data_views.TestDataList.as_view(), name="testdata"),
    url(r'^testdata/add/$', data_views.TestDataAdd.as_view(), name="testdata-add"),
    url(r'^testdata/(?P<pk>[0-9]+)/$', data_views.TestDataDetail.as_view(), name="testdata-detail"),
    url(r'^testdata/(?P<pk>[0-9]+)/update/$', data_views.TestDataUpdate.as_view(), name="testdata-update"),





    ## ajax urls
    url(r'^get_labs_ajax/', data_views.get_labs_ajax, name="get_labs_ajax"),
    url(r'^get_users_ajax/', data_views.get_users_ajax, name="get_users_ajax"),

]

mainApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from Districts import dist_choices
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse
#Create your models here.
class Lab(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(blank=True, null=True)
    thana = models.CharField(max_length=50, blank=True)
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    district = models.CharField(max_length=2, choices=dist_choices)

    class Meta:
        unique_together =('name', 'thana')

    def get_absolute_url(self):
        return reverse('mainapp:lab-detail', kwargs={'pk': self.pk})

    def __str__(self):
        if self.thana:
            return self.name+':'+self.thana
        else:
            return self.name

    def get_data_points_count(self):
        ct=0
        for up in self.userprofile_set.all():
            ct+=up.user.datapoint_set.count()
        return ct

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    designation = models.CharField(max_length=50)
    lab = models.ForeignKey(Lab, null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('mainapp:user-detail', kwargs={'pk': self.pk})

class TestParameter(models.Model):
    parameter_name = models.CharField(max_length=10)
    description = models.TextField()
    added_on = models.DateField(auto_now_add=True)
    added_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return self.parameter_name

    def get_absolute_url(self):
        return reverse('mainapp:parameter-detail', kwargs={'pk': self.pk})


class TestData(models.Model):
    level_choices=(('1','1'),
                    ('2','2'),
                    ('3','3'))
    test_parameter = models.ForeignKey(TestParameter, on_delete=models.CASCADE)
    lot_number = models.CharField(max_length=20)
    control_level = models.CharField(max_length=10, choices=level_choices)
    control_data = models.IntegerField()
    remarks = models.CharField(max_length=50)
    added_by = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, null=True, blank=True)
    district = models.CharField(max_length=50, null=True, blank=True)
    added_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.test_parameter.parameter_name)+'_'+str(self.id)

    def get_absolute_url(self):
        return reverse('mainapp:testdata-detail', kwargs={'pk': self.pk})



@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

mainApp/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *
from Districts import dist_choices
from django.db.models.fields import BLANK_CHOICE_DASH

class UserCreateForm(UserCreationForm):
    lab = forms.ModelChoiceField(Lab.objects.all())
    designation = forms.CharField(max_length=50)
    role = forms.ModelChoiceField(Group.objects.all())
    class Meta:
        model = User
        fields = ('username', 'first_name','last_name','email', 'password1', 'password2', 'lab', 'designation', 'role')

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class PofileUpdateForm(forms.ModelForm):
    role = forms.ModelChoiceField(Group.objects.all(), required=False)
    class Meta:
        model = UserProfile
        fields = ('lab', 'designation', 'role')


class SearchForm(forms.Form):
    any_term = forms.CharField(max_length=50, required=False)
    district = forms.CharField(max_length=50, required=False)
    lab = forms.CharField(max_length=50, required=False)
    user = forms.CharField(max_length=50, required=False)
    patient_name = forms.CharField(max_length=50, required=False)
    patient_age = forms.IntegerField(required=False)

    date_start = forms.CharField(max_length=50, required=False)
    date_end = forms.CharField(max_length=50, required=False)

    class Meta:
        fields =('any_term', 'district','lab','user','date_start','date_end')

mainApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

class IsAdmin(UserPassesTestMixin):
    def test_func(self):
        try:
            return 'admin' == str(self.request.user.groups.all()[0])
        except:
            return False

class LoginRequired(LoginRequiredMixin):
    login_url = '/login/'


class LabsView(IsAdmin, LoginRequired, generic.ListView):
    template_name = 'mainApp/labs.html'
    context_object_name = 'all_labs'
    search_form = SearchForm
    def get_queryset(self):
        return Lab.objects.all()

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context



class LabsDetail(IsAdmin, LoginRequired,generic.DetailView):
    model = Lab
    template_name = 'mainApp/lab_detail.html'
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context

class LabAddView(IsAdmin, LoginRequired,generic.CreateView):
    model = Lab
    fields = ['name','address','thana','district']
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context



class LabUpdate(IsAdmin, LoginRequired, generic.UpdateView):
    model = Lab
    fields = ['name', 'address', 'thana', 'district']
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context


class UsersView( LoginRequired,IsAdmin, generic.ListView):
    template_name = 'mainApp/users.html'
    context_object_name = 'all_users'
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context

    def get_queryset(self):
        return User.objects.all()

class UsersDetail(IsAdmin,LoginRequired,generic.DetailView):
    model = User
    template_name = 'mainApp/user_detail.html'
    search_form = SearchForm

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()

        if 'search_form' not in context:
            context['search_form'] = self.search_form()
            context['district_list'] = district_list
            context['labs'] = labs
            context['users'] = users
        return context


class UserAddView(IsAdmin,LoginRequired, View):

    def get(self, request):
        user_form = UserCreateForm()
        search_form = SearchForm()
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()
        return render(request, 'mainApp/user_form.html',{'form':user_form, 'search_form':search_form,'district_list':district_list,
                                                  'labs':labs,'users':users})
    def post(self, request):
        user_form = UserCreateForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.refresh_from_db()
            user.userprofile.lab = user_form.cleaned_data.get('lab')
            user.userprofile.designation = user_form.cleaned_data.get('designation')
            print user_form.cleaned_data.get('role')
            if str(user_form.cleaned_data.get('role')) == 'admin':
                admin_group = Group.objects.get(name='admin')
                user.groups.add(admin_group)

            if str(user_form.cleaned_data.get('role')) == 'user':
                user_group = Group.objects.get(name='user')
                user.groups.add(user_group)
            user.save()
            return HttpResponseRedirect(reverse('mainapp:user-detail', kwargs={'pk': user.pk}))

        return render(request, 'mainApp/user_form.html', {'form': user_form})



class UserUpdateView(IsAdmin,LoginRequired,View):
    def get(self, request, pk):
        user=User.objects.get(pk=pk)
        user_form = UserUpdateForm(instance=user)
        profile_form = PofileUpdateForm(instance=user.userprofile)
        role = user.groups.all()[0]
        search_form = SearchForm()
        district_list = list(dist_choices)
        labs = Lab.objects.all().values('name')
        users = User.objects.all()
        return render(request, 'mainApp/user_form.html',{'form':user_form,'extra_form':profile_form,'role':role,'search_form':search_form,'district_list':district_list,
                                                  'labs':labs,'users':users})

    def post(self, request, pk ):
        user = User.objects.get(pk=pk)
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = PofileUpdateForm(request.POST, instance=user.userprofile)
        role = user.groups.all()[0]
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            newrole = profile_form.cleaned_data.get('role')
            oldrole = str(user.groups.all()[0])
            if newrole!=None:
                if str(newrole) != str(oldrole):
                    new_role = Group.objects.get(name=newrole)
                    user.groups.clear()
                    user.groups.add(new_role)
                    print newrole, oldrole
            profile_form.save()
            return HttpResponseRedirect(reverse('mainapp:user-detail', kwargs={'pk': user.pk}))

        return render(request, 'mainApp/user_form.html', {'form': user_form,'role':role})

mainApp/templates/mainApp/form-template.html
{% load widget_tweaks %}
{% load replace %}

<span class="text-danger small">
    {{ form.non_field_errors }}
</span>

{% for field in form %}


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">
             {{ field.errors }}
        </span>
        </div>
        <label class="control-label col-sm-2"> {{ field.label_tag }}</label>

        <div class="col-sm-10">{{ field|add_class:'form-control' }}
            {% if field.help_text %}
                <div class="help-block">
                    {% replace search="&amp;#39;" replacement="'" %}
                        {% replace search="&gt;" replacement=">" %}
                            {% replace search="&lt;" replacement="<" %}
                                {{ field.help_text }}
                            {% endreplace %}
                        {% endreplace %}
                    {% endreplace %}
                </div>
            {% endif %}
        </div>

    </div>
{% endfor %}

{% for field in extra_form %}

    {% if field.html_name == 'role' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">
             {{ field.errors }}
        </span>
            </div>
            <label class="control-label col-sm-2"> {{ field.label_tag }}</label>
            <div class="col-sm-10">{{ field|add_class:'form-control' }}
                <div class="help-block">
                    Current Role : {{ role }}
                </div>
            </div>

        </div>
    {% else %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">
             {{ field.errors }}
        </span>
            </div>
            <label class="control-label col-sm-2"> {{ field.label_tag }}</label>
            <div class="col-sm-10">{{ field|add_class:'form-control' }}
                {{ field.help_text }}
            </div>

        </div>
    {% endif %}

{% endfor %}

mainApp/templates/mainApp/kendo_body.html
<td><a href="{% url 'mainapp:data-detail' data.id %}">{{ data }}</a></td>
<td>{{ data.patient_name }}</td>
<td>{{ data.age }}</td>
<td>{{ data.get_gender_display }}</td>
<td>{{ data.total_cholesterol }}</td>
<td>{{ data.high_density_lipid }}</td>
<td>{{ data.low_density_lipid }}</td>
<td>{{ data.tri_glycerides }}</td>
<td>{{ data.date }}</td>
<td><a href="{% url 'mainapp:user-detail' data.added_by.id %}">{{ data.added_by }}</a></td>
<td><a href="{% url 'mainapp:lab-detail' data.lab.id %}">{{ data.lab }}</a></td>

mainApp/templates/mainApp/kendo_columns.html
<th data-field="id">ID</th>
<th data-field="patient_name">Patient Name</th>
<th data-field="patient_age">Patient Age</th>
<th data-field="patient_gender">Gender</th>
<th data-field="tc">Total Cholesterol</th>
<th data-field="hdl">HDL</th>
<th data-field="ldl">LDL</th>
<th data-field="tg">TG</th>
<th data-field="date">Date</th>
<th data-field="user">Added By</th>
<th data-field="lab">Lab</th>

mainApp/templates/mainApp/kendo_columns_qc.html
<th data-field="id">ID</th>
<th data-field="date">Date</th>
<th data-field="test_name">Test Name</th>
<th data-field="level">Level</th>
<th data-field="value">Value</th>
<th data-field="remarks">Remarks</th>
<th data-field="added_by">Added By</th>
<th data-field="lab">Lab</th>

mainApp/templates/mainApp/kendo_scripts.html
{% load static %}

<link rel="stylesheet" href="{% static 'kendo/styles/kendo.common-bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'kendo/styles/kendo.bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'kendo/styles/kendo.bootstrap.mobile.min.css' %}"/>
<script src="{% static 'kendo/js/jszip.min.js' %}"></script>

<script src="{% static 'kendo/js/kendo.all.min.js' %}"></script>

mainApp/templates/mainApp/labs.html
{% extends 'mainApp/base.html' %}
{% block body %}
    <div class="container-fluid display-screen">
        <h3><strong>All Labs</strong></h3>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Lab Name</th>
                <th>Location</th>
                <th>Number of Users</th>
                <th>Number of Datapoints</th>
                <th>Options</th>

            </tr>
            </thead>
            <tbody>
            {% for lab in all_labs %}
                <tr>
                    <td><a href="{% url 'mainapp:lab-detail' lab.id %} ">{{ lab.name }}</a></td>
                    {% if lab.thana %}
                        <td>{{ lab.thana }}, {{ lab.get_district_display }}</td>
                    {% else %}
                        <td>{{ lab.get_district_display }}</td>
                    {% endif %}
                    <td>{{ lab.userprofile_set.count }}</td>
                    <td> {{ lab.get_data_points_count }}
                        </td>
                    <td><a href="{% url 'mainapp:lab-update' lab.id %}" class="btn btn-primary">Edit</a> <a class="btn btn-danger">Delete</a></td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
    <div class="display-print">
    <h3><strong>All Labs</strong></h3>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Lab Name</th>
                <th>Location</th>
                <th>Number of Users</th>
                <th>Number of Datapoints</th>


            </tr>
            </thead>
            <tbody>
            {% for lab in all_labs %}
                <tr>
                    <td>{{ lab.name }}</td>
                    {% if lab.thana %}
                        <td>{{ lab.thana }}, {{ lab.get_district_display }}</td>
                    {% else %}
                        <td>{{ lab.get_district_display }}</td>
                    {% endif %}
                    <td>{{ lab.userprofile_set.count }}</td>
                    <td> {{ lab.get_data_points_count }}
                        </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
{% endblock %}

mainApp/templates/mainApp/qc_form.html
{% extends 'mainApp/base.html' %}

{% block title %}
    {% if url_name == 'qc-add' %}
        New QC
    {% elif url_name == 'data-add-qc' %}
        Adding QC Data
    {% endif %}
{% endblock %}

{% block body %}
    <div class="container-fluid">
    {% if url_name == 'qc-add' %}
        <h3><b>New QC</b></h3>
    {% elif url_name == 'data-add-qc' %}
        <h3><b>Adding QC Data</b></h3>
    {% endif %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'mainApp/form-template.html' %}
                        <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>


                    </form>

                </div>

            </div>

        </div>

    </div>
    </div>
{% endblock %}

mainApp/templates/mainApp/testparameter_form.html
{% extends 'mainApp/base.html' %}

{% block title %}
    {% if url_name == 'parameter-update' %}
        Updating {{ object }}
    {% elif url_name == 'parameter-add' %}
        Adding New Test Parameter
    {% endif %}
{% endblock %}
{% block body %}
    <div class="container-fluid">
        {% if url_name == 'parameter-update' %}
            <h3><b>Updating {{ object }}</b></h3>
    {% elif url_name == 'parameter-add' %}
            <h3><b>Adding New Test Parameter</b></h3>
    {% endif %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'mainApp/form-template.html' %}
                        <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>

                        </div>


                    </form>

                </div>

            </div>

        </div>

    </div>
    </div>
{% endblock %}

mainApp/templates/mainApp/user_detail.html
{% extends 'mainApp/base.html' %}
{% block title %}{{ user }}'s Information{% endblock %}

{% load static %}
{% block extra_head %}
    {% include 'mainApp/kendo_scripts.html' %}
{% endblock %}
{% block body %}
    <div class="container-fluid display-screen">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3><strong>{{ user }}'s Information</strong></h3>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>User Name:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.username }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Email:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.email }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Designation:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.userprofile.designation }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Lab:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.userprofile.lab }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Created On:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.userprofile.created }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <strong>Last Update:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.userprofile.last_updated }}
                    </div>
                </div>


                <div class="row">
                    <div class="col-sm-2">
                        <strong>Number of Datapoints:</strong>
                    </div>
                    <div class="col-sm-5">
                        {{ user.datapoint_set.count }}
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                <a href="{% url 'mainapp:user-update' user.id %}" class="btn btn-primary">Edit</a>
                <a class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
    <div class="container-fluid display-screen">

        <table id="grid">

            <thead>
            <tr>

            </tr>
            </thead>
            <tbody>



            </tbody>
        </table>

    {% include 'mainApp/kendo_components.html' %}

    </div>
    <div class="display-print">
        <h3><strong>{{ user }}'s Information</strong></h3>
        <table>
            <tbody>
            <tr>
                <td>User Name:</td>
                <td>{{ user }}</td>
            </tr>
            <tr>
                <td>
                    <strong>Email:</strong>
                </td>
                <td>
                    {{ user.email }}
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Designation:</strong>
                </td>
                <td>
                    {{ user.userprofile.designation }}
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Lab:</strong>
                </td>
                <td>
                    {{ user.userprofile.lab }}
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Created On:</strong>
                </td>
                <td>
                    {{ user.userprofile.created }}
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Last Update:</strong>
                </td>
                <td>
                    {{ user.userprofile.last_updated }}
                </td>
            </tr>


            <tr>
                <td>
                    <strong>Number of Datapoints:</strong>
                </td>
                <td>
                    {{ user.datapoint_set.count }}
                </td>
            </tr>
            </tbody>
        </table>
    <table class="table table-bordered">

            <thead>
            <tr>

            </tr>
            </thead>
            <tbody>



            </tbody>
        </table>
    </div>
{% endblock %}

mainApp/templates/mainApp/users.html
{% extends 'mainApp/base.html' %}
{% block body %}
    <div class="container-fluid display-screen">
        <h3><strong>All Users</strong></h3>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Lab</th>
                    <th>Number of Datapoints</th>
                    <th>Options</th>
                </tr>
                </thead>
                <tbody>
                {% for user in all_users %}
                {% if user.username != 'ruhshan' %}

                    <tr>
                        <td>
                            <a href="{% url 'mainapp:user-detail' user.id %}">
                            {% if  user.first_name and user.last_name %}
                                {{ user.first_name }} {{ user.last_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </a></td>
                        <td>{{ user.email }}</td>

                        <td>
                            <a href="{% url 'mainapp:lab-detail' user.userprofile.lab.id %}">{{ user.userprofile.lab }}</a>
                        </td>
                        <td>{{ user.datapoint_set.count }}</td>
                        <td>
                            <a href="{% url 'mainapp:user-update' user.id %}" class="btn btn-primary">Edit</a>
                            <a class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="display-print">
    <h3><strong>All Users</strong></h3>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Lab</th>
                    <th>Number of Datapoints</th>

                </tr>
                </thead>
                <tbody>
                {% for user in all_users %}

                    <tr>
                    {% if user.username != 'ruhshan' %}
                        <td>

                            {% if  user.first_name and user.last_name %}
                                {{ user.first_name }} {{ user.last_name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </td>
                        <td>{{ user.email }}</td>

                        <td>
                            {{ user.userprofile.lab }}
                        </td>
                        <td>{{ user.datapoint_set.count }}</td>

                    </tr>

                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}